// TODO CONSTANTS
export const INCREMENT_GLOBAL_COUNT = "INCREMENT_GLOBAL_COUNT";
export const DECREMENT_GLOBAL_COUNT = "DECREMENT_GLOBAL_COUNT";
export const ADD_TODO_INIT = "ADD_TODO_INIT";
export const ADD_TODO = "ADD_TODO";
